# Generated by Django 4.0.6 on 2022-08-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_try', '0002_file_upload_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
