# Generated by Django 4.0 on 2022-08-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('file_type', models.CharField(max_length=10)),
                ('upload_timestamp_date', models.DateField(auto_now_add=True, null=True)),
                ('upload_timestamp_time', models.TimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
