# Generated by Django 4.0 on 2022-08-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_try', '0002_remove_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
